### ISSUE TITLE
How to change the base path for swagger ui

### ISSUE THREAD

**Issue by ctippur** [kaizhu256/node-swagger-ui-lite#1]
This is more my own issue. When I try the "try it out!" button, I always get https://localhost:3000

Wondering if this can be tweaked to get a specified url instead?
- Shekar

**Comment by ctippur** [comment]
I also see a validator error link at the bottom. Wondering how to avoid that.
<img width="184" alt="screen shot 2016-08-17 at 12 28 25" src="https://cloud.githubusercontent.com/assets/2225047/17750221/2181fa40-6476-11e6-9127-07cc9c3821ac.png">

Thanks

**Comment by kaizhu256** [comment]
hi ctipper
1. the localhost:3000 is from your own swagger json-config file.  i attached a screen-capture so you can figure out where to look for it in your own swagger config file.

![screen shot 2016-08-18 at 11 57 22](https://cloud.githubusercontent.com/assets/280571/17787313/74e75cee-653d-11e6-88be-89c84ac59fef.png)


2.  your swagger config file is failing the online validator @ https://online.swagger.io/validator
you can disable the online validator by disabling the source code @ https://github.com/kaizhu256/node-swagger-ui-lite/blob/alpha/swagger-ui.rollup.js.  in screenshot of source code code below, change the highlighted part to an empty string ""

![screen shot 2016-08-18 at 12 15 46](https://cloud.githubusercontent.com/assets/280571/17787342/98434a7c-653d-11e6-8370-0f1ec71ef507.png)

**Comment by ctippur** [comment]
@kaizhu256 - Thanks a lot.
Your recommendation works.

- Shekar

**Comment by kaizhu256** [comment]
np : )
